### ISSUE TITLE
Rethink database state management

### ISSUE THREAD

**Issue by jstet** [CorrelAid/fds_dashboard#16]
Current idea is to grab all of FragDenStaats data from the api with code in [this folder](https://github.com/CorrelAid/fds_dashboard/tree/main/db/python_scripts) and put it in a database with an init script and then afterwards to update the data  with [this](https://github.com/CorrelAid/fds_dashboard/tree/main/update_service).  

I wonder whether we could combine these two containers and create one container that we could also already host somewhere that continuously updates the data. @jandix idea was to use [celery](https://docs.celeryq.dev/en/stable/). 

Running the script that grabs the initial data takes hours, so we already run it [remotely on a server](https://github.com/jstet/prescript) but then just copy the outputted data to the repo.

**Comment by jandix** [comment]
Hi @jstet, Celery is probably a slight overshoot if you have only one task you want to schedule. The [docs](https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html#starting-the-scheduler) recommend that you should set up two instances if you want to schedule jobs periodically. Alternatively, you could use [RQ](https://python-rq.org/) which has a much simpler interface. However, for both solutions, you need a message queue (e.g.: Redis) which introduces an additional service you have to maintain and monitor. Maybe you could just use a Cron job on the host systems that starts the Docker Container once a day? If you execute the script the Container will be automatically destroyed (using the --rm flag).

Additionally, you might want to introduce something to monitor the jobs so that you can easily check if the job is running as expected. If you decide to use Celery you could use [Flower](https://flower.readthedocs.io/en/latest/) which provides a web interface to monitor all tasks scheduled in Celery. Alternatively or additionally, you can also check the free tier of [Sentry](https://sentry.io) because it also includes alerting.
